server:
  port: 8081
  servlet:
    context-path: /api/v1

spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5433}/postgres?currentSchema=public
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:123456789}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 100MB

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

open:
  api:
    title: The Ecommerce API
    version: 1.0.0
    description: The Ecommerce API
    serverUrl: http://localhost:8081/api/v1/
    serverDescription: Localhost
    license: Apache License Version 2.0
    licenseUrl: http://www.apache.org/licenses/LICENSE-2.0.html
    servers:
      url: http://localhost:8081/api/v1/swagger-ui.html

